project:
  type: website
  title: The Multepal Project
  output-dir: docs
  resources: resources

website:
  title: "Multepal"
  navbar:
    logo: "resources/logo.png"
    background: "#fdf1e1"
    right:
      - href: index.qmd
        text: Home
      - href: pages/projects.qmd
        text: Projects
      - href: pages/team.qmd
        text: People
      - href: pages/dev.qmd
        text: Development
      - href: pages/publications.qmd
        text: Publications

    # sidebar:
    #   - id

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true