project:
  type: website
  title: Multepal
  output-dir: docs
  resources: resources

website:
  title: "The Multepal Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: team.qmd
        text: Team
      - href: variorum.qmd
        text: Variorum
  open-graph: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
