project:
  type: website
  title: Multepal
  output-dir: docs
  resources: resources

website:
  title: "Multepal"
  navbar:
    logo: "resources/logo.png"
    right:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: team.qmd
        text: People
      - href: variorum.qmd
        text: Variorum
      - href: about.qmd
        text: About
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true